baseURL = 'https://nishanth.blog/'
languageCode = 'en-us'
title = 'Nishanth Sudharsanam'
theme = 'ananke'
sectionPagesMenu = 'main'

[[menus.main]]
  name = 'Me'
  url = '/me/'
  weight = 1

[services.googleAnalytics]
  ID = 'G-JK2H8TS75N'

[params]
  images = ['icon-512.png']
  [params.ananke]
    custom_css = ['custom.css']
