baseURL = 'https://nishanth.me/'
languageCode = 'en-us'
title = 'Nishanth Sudharsanam'
theme = 'ananke'
sectionPagesMenu = 'main'

[markup.goldmark.renderer]
  unsafe = true

[[menus.main]]
  name = 'Me'
  url = '/me/'
  weight = 1
